window.GALAID_ERROR_RECIPES = [
  {
    id: "directx-legacy",
    title: "DirectX 旧组件",
    category: "runtime",
    level: "warning",
    patterns: ["d3dx\\d+_\\d+\\.dll", "\\bd3dx\\b", "xinput1_3\\.dll", "dsound\\.dll", "dinput8?\\.dll", "directx"],
    cause: "老游戏可能依赖 DirectX 9 时代的 D3DX、XInput、DirectSound 或 DirectInput 组件，新系统自带 DirectX 12 不代表包含这些旧 DLL。",
    action: "安装 DirectX End-User Runtime，并确认游戏文件没有被杀软隔离。",
    checklist: ["安装 DirectX End-User Runtime", "重新完整解压游戏", "确认报错中的 DLL 不在隔离区"],
  },
  {
    id: "visual-cpp-redist",
    title: "VC++ 运行库",
    category: "runtime",
    level: "warning",
    patterns: ["msvcr\\d+\\.dll", "msvcp\\d+\\.dll", "vcruntime\\d+\\.dll", "visual c\\+\\+", "vc\\+\\+", "side-by-side"],
    cause: "启动器或引擎依赖 Microsoft Visual C++ Redistributable。老 galgame 即使在 64 位系统上也常需要 x86 版本。",
    action: "安装 Microsoft Visual C++ Redistributable x86/x64，再从推荐启动入口重试。",
    checklist: ["安装 x86 运行库", "必要时补装 x64 运行库", "避免把 vcredist 当作游戏入口"],
  },
  {
    id: "rpgmaker-rtp",
    title: "RPG Maker RTP",
    category: "runtime",
    level: "warning",
    patterns: ["\\brtp\\b", "\\brgss\\d*", "rpg maker", "rpgツクール", "rpgmaker"],
    cause: "RPG Maker 旧版项目可能没有随游戏打包完整 RTP 素材或 RGSS 运行环境。",
    action: "安装与游戏版本对应的 RPG Maker RTP，或确认发行包是否包含 RTP 文件。",
    checklist: ["确认游戏使用的 RPG Maker 版本", "安装对应 RTP", "重新从 Game.exe 启动"],
  },
  {
    id: "locale-encoding",
    title: "日区与文本编码",
    category: "locale",
    level: "warning",
    patterns: ["文字化け", "乱码", "mojibake", "locale", "\\?{4,}", "\\uFFFD", "区域设置", "日区"],
    cause: "脚本、文件名或字体可能按日文系统区域保存，非日区环境下会乱码、找不到文件或直接闪退。",
    action: "尝试日区环境或 Locale Emulator，并把游戏移动到英文短路径。",
    checklist: ["移动到 C:/Games/VNName", "使用日区环境或 Locale Emulator", "安装日文字体"],
  },
  {
    id: "missing-file",
    title: "缺文件或路径读取失败",
    category: "files",
    level: "warning",
    patterns: ["not found", "cannot find", "missing", "failed to load", "no such file", "找不到", "缺少", "読み込め"],
    cause: "游戏可能没有完整解压、分卷缺失、路径编码不兼容，或启动时工作目录不正确。",
    action: "重新完整解压，确认分卷齐全，并使用配置页推荐的工作目录启动。",
    checklist: ["补齐所有分卷", "从第一分卷重新解压", "使用推荐启动配置"],
  },
  {
    id: "permission-write",
    title: "权限或写入位置",
    category: "system",
    level: "warning",
    patterns: ["access denied", "permission denied", "unauthorized", "拒绝访问", "权限", "書き込"],
    cause: "游戏可能无法写入存档、配置或补丁文件，常见于 Program Files、受保护目录或同步盘目录。",
    action: "把游戏移动到用户可写目录或 C:/Games；必要时再尝试管理员权限。",
    checklist: ["避开 Program Files", "避开系统盘受保护目录", "确认存档目录可写"],
  },
  {
    id: "archive-incomplete",
    title: "压缩包损坏或分卷不完整",
    category: "package",
    level: "warning",
    patterns: ["crc failed", "unexpected end", "checksum", "next volume", "corrupt", "archive is damaged", "压缩包损坏", "校验失败", "分卷"],
    cause: "压缩包可能下载不完整、缺少后续分卷，或只解压了其中一个分卷。",
    action: "补齐所有分卷后从第一分卷重新解压；不要在压缩软件预览窗口里直接运行游戏。",
    checklist: ["确认 part1/part2 或 .001/.002 都在同一目录", "重新校验下载文件", "从第一分卷解压"],
  },
  {
    id: "web-local-files",
    title: "网页 VN 本地文件限制",
    category: "web",
    level: "warning",
    patterns: ["cors", "cross origin", "file://", "xmlhttprequest", "fetch", "blocked by client", "origin 'null'"],
    cause: "TyranoScript 或 HTML5 VN 直接用 file:// 打开时，浏览器可能禁止读取脚本、图片或音频资源。",
    action: "在游戏目录启动本地服务器，再从浏览器访问 index.html。",
    checklist: ["确认 index.html 所在目录", "使用本地服务器打开", "避免直接拖进浏览器运行"],
  },
  {
    id: "unity-runtime",
    title: "Unity 文件缺失",
    category: "engine",
    level: "warning",
    patterns: ["unityplayer\\.dll", "gameassembly\\.dll", "monobleedingedge", "unity crash", "unityplayer"],
    cause: "Unity 游戏的 exe、UnityPlayer.dll、GameAssembly.dll 或同名 _Data 文件夹可能没有放在一起。",
    action: "确认 exe 与 _Data 文件夹同级，并重新完整解压缺失的 Unity 运行文件。",
    checklist: ["检查 UnityPlayer.dll", "检查同名 _Data 文件夹", "不要只复制 exe"],
  },
  {
    id: "disc-required",
    title: "光盘或镜像未挂载",
    category: "package",
    level: "warning",
    patterns: ["please insert", "insert disc", "no disc", "cd-rom", "dvd-rom", "ディスク", "光盘", "光碟"],
    cause: "老游戏可能需要先挂载安装镜像，或启动时检查光盘文件。",
    action: "先挂载或解包镜像，再从安装后的完整游戏目录启动。",
    checklist: ["确认 ISO/CUE/MDS 等镜像存在", "先挂载或解包镜像", "从安装后的目录启动"],
  },
  {
    id: "dotnet-runtime",
    title: ".NET 运行环境",
    category: "runtime",
    level: "warning",
    patterns: ["\\.net framework", "dotnet", "mscoree\\.dll", "clr20r3", "system\\.io", "system\\.windows\\.forms"],
    cause: "启动器、配置工具或汉化补丁工具可能依赖 .NET Framework。",
    action: "安装报错中指定的 .NET Framework 版本；如果主游戏入口不需要该工具，可先尝试直接运行游戏 exe。",
    checklist: ["确认报错来自启动器还是游戏本体", "安装指定 .NET Framework", "尝试直接运行主程序"],
  },
];
